#include "PDBHeaderGenerator.h"
#include "PDBParser.h"
#include <algorithm>
#include <codecvt>
#include <fstream>
#include <locale>
#include <set>

bool PDBHeaderGenerator::GenerateClassHeader(const ClassInfo& classInfo, const std::wstring& filePath, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    ExportSettings defaultSettings;
    return GenerateClassHeader(classInfo, filePath, defaultSettings, numberMode, expandBaseClasses, moduleInfo);
}

bool PDBHeaderGenerator::GenerateAllHeaders(const ModuleInfo& moduleInfo, const std::wstring& directoryPath, NumberDisplayMode numberMode, bool expandBaseClasses) {
    ExportSettings defaultSettings;
    return GenerateAllHeaders(moduleInfo, directoryPath, defaultSettings, numberMode, expandBaseClasses);
}

bool PDBHeaderGenerator::GenerateClassHeader(const ClassInfo& classInfo, const std::wstring& filePath, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    std::wofstream file;
    
    file.open(filePath);
    
    if (!file.is_open()) {
        return false;
    }

    file << L"// Auto-generated header file\r\n";
    file << L"// Generated by PDBViewer\r\n\r\n";
    file << L"#pragma once\r\n\r\n";

    if (classInfo.isUnion) {
        file << GenerateUnionDeclaration(classInfo, settings, numberMode, expandBaseClasses, moduleInfo);
    } else if (classInfo.isStruct) {
        file << GenerateStructDeclaration(classInfo, settings, numberMode, expandBaseClasses, moduleInfo);
    } else {
        file << GenerateClassDeclaration(classInfo, settings, numberMode, expandBaseClasses, moduleInfo);
    }

    return true;
}

bool PDBHeaderGenerator::GenerateAllHeaders(const ModuleInfo& moduleInfo, const std::wstring& directoryPath, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses) {
    bool success = true;

    for (const auto& cls : moduleInfo.classes) {
        std::wstring filePath = directoryPath + L"\\" + EscapeForHeader(settings.flattenNamespaces ? FlattenName(cls.name) : cls.name) + L".h";
        if (!GenerateClassHeader(cls, filePath, settings, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }

    for (const auto& str : moduleInfo.structs) {
        std::wstring filePath = directoryPath + L"\\" + EscapeForHeader(settings.flattenNamespaces ? FlattenName(str.name) : str.name) + L".h";
        if (!GenerateClassHeader(str, filePath, settings, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }

    for (const auto& uni : moduleInfo.unions) {
        std::wstring filePath = directoryPath + L"\\" + EscapeForHeader(settings.flattenNamespaces ? FlattenName(uni.name) : uni.name) + L".h";
        if (!GenerateClassHeader(uni, filePath, settings, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }

    return success;
}

std::wstring PDBHeaderGenerator::GenerateClassDeclaration(const ClassInfo& classInfo, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    ExportSettings defaultSettings;
    return GenerateClassDeclaration(classInfo, defaultSettings, numberMode, expandBaseClasses, moduleInfo);
}

std::wstring PDBHeaderGenerator::GenerateStructDeclaration(const ClassInfo& structInfo, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    ExportSettings defaultSettings;
    return GenerateStructDeclaration(structInfo, defaultSettings, numberMode, expandBaseClasses, moduleInfo);
}

std::wstring PDBHeaderGenerator::GenerateUnionDeclaration(const ClassInfo& unionInfo, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    ExportSettings defaultSettings;
    return GenerateUnionDeclaration(unionInfo, defaultSettings, numberMode, expandBaseClasses, moduleInfo);
}

std::wstring PDBHeaderGenerator::GenerateEnumDeclaration(const EnumInfo& enumInfo, NumberDisplayMode numberMode) {
    ExportSettings defaultSettings;
    return GenerateEnumDeclaration(enumInfo, defaultSettings, numberMode);
}

std::wstring PDBHeaderGenerator::GeneratePureCStructDeclaration(const ClassInfo& classInfo, const ExportSettings& settings, NumberDisplayMode numberMode, const ModuleInfo* moduleInfo) {
    std::wostringstream ss;
    std::wstring className = settings.flattenNamespaces ? FlattenName(classInfo.name) : EscapeForHeader(classInfo.name);

    std::vector<MemberVariableInfo> allMembers;

    if (moduleInfo) {
        std::vector<std::pair<const ClassInfo*, LONG>> classChain;
        const ClassInfo* current = &classInfo;
        LONG currentOffset = 0;
        while (current) {
            classChain.push_back({current, currentOffset});
            if (current->baseClasses.empty()) {
                break;
            }
            const BaseClassInfo& firstBase = current->baseClasses[0];
            currentOffset += firstBase.offset;
            current = FindClassInfo(firstBase.name, moduleInfo);
        }

        for (auto it = classChain.rbegin(); it != classChain.rend(); ++it) {
            const ClassInfo* cls = it->first;
            LONG baseOffset = it->second;
            for (const auto& member : cls->members) {
                MemberVariableInfo newMember = member;
                if (member.offset >= 0) {
                    newMember.offset = member.offset + baseOffset;
                }
                allMembers.push_back(newMember);
            }
        }
    } else {
        allMembers = classInfo.members;
    }

    if (classInfo.isUnion) {
        ss << L"union " << className << L"\r\n{\r\n";
    } else {
        ss << L"struct " << className << L"\r\n{\r\n";
    }

    for (const auto& member : allMembers) {
        std::wstring memberType = ProcessTypeName(member.type, settings);
        ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
        if (member.offset >= 0) {
            ss << L" // " << FormatOffset(member.offset, numberMode);
        }
        ss << L"\r\n";
    }

    ss << L"};\r\n";

    return ss.str();
}

bool PDBHeaderGenerator::GenerateEnumsHeader(const ModuleInfo& moduleInfo, const std::wstring& filePath, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses) {
    std::wofstream file;
    
    file.open(filePath);
    
    if (!file.is_open()) {
        return false;
    }

    file << L"// Auto-generated header file with all classes/structs/unions\r\n";
    file << L"// Generated by PDB Insight\r\n\r\n";
    file << L"#pragma once\r\n\r\n";

    std::set<std::wstring> exportedNames;

    if (settings.includeEnumsInEnumsH) {
        for (const auto& enm : moduleInfo.enums) {
            std::wstring enumName = settings.flattenNamespaces ? FlattenName(enm.name) : EscapeForHeader(enm.name);
            if (exportedNames.find(enumName) == exportedNames.end()) {
                exportedNames.insert(enumName);
                file << GenerateEnumDeclaration(enm, settings, numberMode);
                file << L"\r\n\r\n";
            }
        }
    }

    if (settings.idaCompatible) {
        for (const auto& cls : moduleInfo.classes) {
            std::wstring className = settings.flattenNamespaces ? FlattenName(cls.name) : EscapeForHeader(cls.name);
            if (exportedNames.find(className) == exportedNames.end()) {
                exportedNames.insert(className);
                std::wstring structDecl = GeneratePureCStructDeclaration(cls, settings, numberMode, &moduleInfo);
                file << structDecl;
                file << L"\r\n\r\n";
            }
        }

        for (const auto& str : moduleInfo.structs) {
            std::wstring structName = settings.flattenNamespaces ? FlattenName(str.name) : EscapeForHeader(str.name);
            if (exportedNames.find(structName) == exportedNames.end()) {
                exportedNames.insert(structName);
                std::wstring structDecl = GeneratePureCStructDeclaration(str, settings, numberMode, &moduleInfo);
                file << structDecl;
                file << L"\r\n\r\n";
            }
        }

        for (const auto& uni : moduleInfo.unions) {
            std::wstring unionName = settings.flattenNamespaces ? FlattenName(uni.name) : EscapeForHeader(uni.name);
            if (exportedNames.find(unionName) == exportedNames.end()) {
                exportedNames.insert(unionName);
                std::wstring unionDecl = GeneratePureCStructDeclaration(uni, settings, numberMode, &moduleInfo);
                file << unionDecl;
                file << L"\r\n\r\n";
            }
        }
    } else {
        for (const auto& cls : moduleInfo.classes) {
            std::wstring className = settings.flattenNamespaces ? FlattenName(cls.name) : EscapeForHeader(cls.name);
            if (exportedNames.find(className) == exportedNames.end()) {
                exportedNames.insert(className);
                std::wstring classDecl = GenerateClassDeclaration(cls, settings, numberMode, expandBaseClasses, &moduleInfo);
                file << classDecl;
                file << L"\r\n\r\n";
            }
        }

        for (const auto& str : moduleInfo.structs) {
            std::wstring structName = settings.flattenNamespaces ? FlattenName(str.name) : EscapeForHeader(str.name);
            if (exportedNames.find(structName) == exportedNames.end()) {
                exportedNames.insert(structName);
                std::wstring structDecl = GenerateStructDeclaration(str, settings, numberMode, expandBaseClasses, &moduleInfo);
                file << structDecl;
                file << L"\r\n\r\n";
            }
        }

        for (const auto& uni : moduleInfo.unions) {
            std::wstring unionName = settings.flattenNamespaces ? FlattenName(uni.name) : EscapeForHeader(uni.name);
            if (exportedNames.find(unionName) == exportedNames.end()) {
                exportedNames.insert(unionName);
                std::wstring unionDecl = GenerateUnionDeclaration(uni, settings, numberMode, expandBaseClasses, &moduleInfo);
                file << unionDecl;
                file << L"\r\n\r\n";
            }
        }
    }

    file.close();
    return true;
}

std::wstring PDBHeaderGenerator::FormatNumber(ULONGLONG value, NumberDisplayMode mode) {
    std::wostringstream ss;
    
    switch (mode) {
        case NUMBER_HEX:
            ss << L"0x" << std::hex << value;
            break;
        case NUMBER_DEC:
            ss << std::dec << value;
            break;
        case NUMBER_BOTH:
            ss << L"0x" << std::hex << value << L" (" << std::dec << value << L")";
            break;
    }
    
    return ss.str();
}

std::wstring PDBHeaderGenerator::FormatOffset(LONG offset, NumberDisplayMode mode) {
    return FormatNumber(static_cast<ULONGLONG>(offset), mode);
}

const ClassInfo* PDBHeaderGenerator::FindClassInfo(const std::wstring& className, const ModuleInfo* moduleInfo) {
    if (!moduleInfo) return nullptr;
    
    for (const auto& cls : moduleInfo->classes) {
        if (cls.name == className) return &cls;
    }
    for (const auto& str : moduleInfo->structs) {
        if (str.name == className) return &str;
    }
    for (const auto& uni : moduleInfo->unions) {
        if (uni.name == className) return &uni;
    }
    return nullptr;
}

std::wstring PDBHeaderGenerator::GenerateClassDeclaration(const ClassInfo& classInfo, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    std::wostringstream ss;
    std::wstring className = settings.flattenNamespaces ? FlattenName(classInfo.name) : EscapeForHeader(classInfo.name);

    ss << L"class " << className;

    if (!classInfo.baseClasses.empty()) {
        ss << L" : ";
        for (size_t i = 0; i < classInfo.baseClasses.size(); ++i) {
            if (i > 0) ss << L", ";
            const auto& base = classInfo.baseClasses[i];
            std::wstring baseName = settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name);
            ss << AccessTypeToString(base.access) << L" " << baseName;
        }
    }

    ss << L"\r\n{\r\n";

    if (expandBaseClasses && !classInfo.baseClasses.empty() && moduleInfo) {
        for (const auto& base : classInfo.baseClasses) {
            const ClassInfo* baseClass = FindClassInfo(base.name, moduleInfo);
            if (baseClass) {
                ss << L"\r\n    // --- Base class: " << (settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name)) << L" --- \r\n";
                
                AccessType currentAccess = PDB_ACCESS_PRIVATE;
                for (const auto& member : baseClass->members) {
                    if (member.access != currentAccess) {
                        currentAccess = member.access;
                        ss << L"\r\n    " << AccessTypeToString(currentAccess) << L":\r\n";
                    }
                    std::wstring memberType = ProcessTypeName(member.type, settings);
                    ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
                    if (member.offset >= 0) {
                        ss << L" // " << FormatOffset(member.offset + base.offset, numberMode);
                    }
                    ss << L"\r\n";
                }
                ss << L"\r\n    // --- End of base class: " << (settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name)) << L" --- \r\n";
            }
        }
    }

    if (!classInfo.members.empty()) {
        if (expandBaseClasses && !classInfo.baseClasses.empty()) {
            ss << L"\r\n    // --- Current class members --- \r\n";
        }
        
        AccessType currentAccess = PDB_ACCESS_PRIVATE;
        for (const auto& member : classInfo.members) {
            if (member.access != currentAccess) {
                currentAccess = member.access;
                ss << L"\r\n    " << AccessTypeToString(currentAccess) << L":\r\n";
            }
            std::wstring memberType = ProcessTypeName(member.type, settings);
            ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
            if (member.offset >= 0) {
                ss << L" // " << FormatOffset(member.offset, numberMode);
            }
            ss << L"\r\n";
        }
    }

    ss << L"};\r\n";

    return ss.str();
}

std::wstring PDBHeaderGenerator::GenerateStructDeclaration(const ClassInfo& structInfo, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    std::wostringstream ss;
    std::wstring structName = settings.flattenNamespaces ? FlattenName(structInfo.name) : EscapeForHeader(structInfo.name);

    ss << L"struct " << structName;

    if (!structInfo.baseClasses.empty()) {
        ss << L" : ";
        for (size_t i = 0; i < structInfo.baseClasses.size(); ++i) {
            if (i > 0) ss << L", ";
            const auto& base = structInfo.baseClasses[i];
            std::wstring baseName = settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name);
            ss << L" " << baseName;
        }
    }

    ss << L"\r\n{\r\n";

    if (expandBaseClasses && !structInfo.baseClasses.empty() && moduleInfo) {
        for (const auto& base : structInfo.baseClasses) {
            const ClassInfo* baseClass = FindClassInfo(base.name, moduleInfo);
            if (baseClass) {
                ss << L"\r\n    // --- Base struct: " << (settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name)) << L" --- \r\n";
                
                for (const auto& member : baseClass->members) {
                    std::wstring memberType = ProcessTypeName(member.type, settings);
                    ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
                    if (member.offset >= 0) {
                        ss << L" // " << FormatOffset(member.offset + base.offset, numberMode);
                    }
                    ss << L"\r\n";
                }
                ss << L"\r\n    // --- End of base struct: " << (settings.flattenNamespaces ? FlattenName(base.name) : EscapeForHeader(base.name)) << L" --- \r\n";
            }
        }
    }

    if (!structInfo.members.empty()) {
        if (expandBaseClasses && !structInfo.baseClasses.empty()) {
            ss << L"\r\n    // --- Current struct members --- \r\n";
        }
        
        for (const auto& member : structInfo.members) {
            std::wstring memberType = ProcessTypeName(member.type, settings);
            ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
            if (member.offset >= 0) {
                ss << L" // " << FormatOffset(member.offset, numberMode);
            }
            ss << L"\r\n";
        }
    }

    ss << L"};\r\n";

    return ss.str();
}

std::wstring PDBHeaderGenerator::GenerateUnionDeclaration(const ClassInfo& unionInfo, const ExportSettings& settings, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    std::wostringstream ss;
    std::wstring unionName = settings.flattenNamespaces ? FlattenName(unionInfo.name) : EscapeForHeader(unionInfo.name);

    ss << L"union " << unionName << L"\r\n{\r\n";

    if (!unionInfo.members.empty()) {
        for (const auto& member : unionInfo.members) {
            std::wstring memberType = ProcessTypeName(member.type, settings);
            ss << L"    " << memberType << L" " << EscapeForHeader(member.name) << L";";
            if (member.offset >= 0) {
                ss << L" // " << FormatOffset(member.offset, numberMode);
            }
            ss << L"\r\n";
        }
    }

    ss << L"};\r\n";

    return ss.str();
}

std::wstring PDBHeaderGenerator::AccessTypeToString(AccessType access) {
    switch (access) {
        case PDB_ACCESS_PUBLIC: return L"public";
        case PDB_ACCESS_PROTECTED: return L"protected";
        case PDB_ACCESS_PRIVATE: return L"private";
        default: return L"";
    }
}

std::wstring PDBHeaderGenerator::EscapeForHeader(const std::wstring& str) {
    std::wstring result;
    for (wchar_t c : str) {
        if (c == L' ' || c == L':' || c == L'-' || c == L'<' || c == L'>' || 
            c == L'(' || c == L')' || c == L',') {
            result += L'_';
        } else if (c == L'*') {
            result += L"_ptr";
        } else {
            result += c;
        }
    }
    return result;
}

std::wstring PDBHeaderGenerator::FlattenName(const std::wstring& name) {
    std::wstring result;
    for (wchar_t c : name) {
        if (c == L':' || c == L'<' || c == L'>' || c == L',' || c == L' ' || c == L'(' || c == L')' || c == L'&' || c == L'*' || c == L'-') {
            result += L'_';
        } else {
            result += c;
        }
    }
    return result;
}

std::wstring PDBHeaderGenerator::ProcessTypeName(const std::wstring& name, const ExportSettings& settings) {
    std::wstring result = name;
    
    if (settings.flattenNamespaces) {
        result = FlattenName(result);
    }
    
    if (settings.removeVoidParams) {
        result = RemoveVoidParams(result);
    }
    
    return result;
}

std::wstring PDBHeaderGenerator::RemoveVoidParams(const std::wstring& signature) {
    std::wstring result = signature;
    
    size_t pos = 0;
    while ((pos = result.find(L"(void)", pos)) != std::wstring::npos) {
        result.replace(pos, 6, L"()");
        pos += 2;
    }
    
    return result;
}

std::wstring PDBHeaderGenerator::GenerateEnumDeclaration(const EnumInfo& enumInfo, const ExportSettings& settings, NumberDisplayMode numberMode) {
    std::wostringstream ss;
    std::wstring enumName = settings.flattenNamespaces ? FlattenName(enumInfo.name) : EscapeForHeader(enumInfo.name);
    
    ss << L"enum " << enumName;
    if (!enumInfo.underlyingType.empty()) {
        ss << L" : " << enumInfo.underlyingType;
    }
    ss << L"\r\n{\r\n";
    
    for (size_t i = 0; i < enumInfo.values.size(); ++i) {
        ss << L"    " << enumInfo.values[i].name << L" = " << FormatNumber(static_cast<ULONGLONG>(enumInfo.values[i].value), numberMode);
        if (i < enumInfo.values.size() - 1) {
            ss << L",";
        }
        ss << L"\r\n";
    }
    
    ss << L"};\r\n";
    
    return ss.str();
}
