#include "ExportEnhancer.h"
#include "PDBHeaderGenerator.h"
#include <algorithm>
#include <regex>
#include <fstream>

ExportOptions ExportEnhancer::GetDefaultOptions() {
    ExportOptions options;
    options.flattenNamespaces = true;
    options.removeVoidParams = true;
    options.generateTypeDefs = false;
    options.includeAddressComments = false;
    options.generateEnumValueComments = false;
    return options;
}

std::wstring ExportEnhancer::FlattenName(const std::wstring& name) {
    std::wstring result = name;
    std::replace(result.begin(), result.end(), L':', L'_');
    return result;
}

std::wstring ExportEnhancer::RemoveVoidFromParams(const std::wstring& signature) {
    std::wstring result = signature;
    size_t pos = result.find(L"(void)");
    if (pos != std::wstring::npos) {
        result.replace(pos, 6, L"()");
    }
    return result;
}

std::wstring ExportEnhancer::GenerateIDACompatibleHeader(const ModuleInfo& moduleInfo, const ExportOptions& options) {
    std::wostringstream ss;
    
    ss << L"// IDA Compatible Header File\r\n";
    ss << L"// Generated by PDB Insight\r\n";
    ss << L"// File: " << moduleInfo.pdbFileName << L"\r\n\r\n";
    ss << L"#pragma once\r\n\r\n";
    
    if (options.generateTypeDefs) {
        ss << L"// Type Definitions\r\n";
        ss << L"typedef unsigned char uint8_t;\r\n";
        ss << L"typedef unsigned short uint16_t;\r\n";
        ss << L"typedef unsigned int uint32_t;\r\n";
        ss << L"typedef unsigned long long uint64_t;\r\n\r\n";
    }
    
    ss << L"// Enums\r\n";
    for (const auto& enm : moduleInfo.enums) {
        ss << PDBHeaderGenerator::GenerateEnumDeclaration(enm, NUMBER_HEX);
        ss << L"\r\n";
    }
    
    ss << L"\r\n// Structs\r\n";
    for (const auto& cls : moduleInfo.classes) {
        std::wstring className = options.flattenNamespaces ? FlattenName(cls.name) : cls.name;
        ss << L"class " << className << L";\r\n";
    }
    
    ss << L"\r\n// Functions\r\n";
    for (const auto& func : moduleInfo.functions) {
        std::wstring funcName = options.flattenNamespaces ? FlattenName(func.name) : func.name;
        
        std::wostringstream signatureStream;
        signatureStream << func.returnType << L" " << funcName << L"(";
        
        for (size_t i = 0; i < func.parameters.size(); i++) {
            if (i > 0) {
                signatureStream << L", ";
            }
            signatureStream << func.parameters[i].type;
            if (!func.parameters[i].name.empty()) {
                signatureStream << L" " << func.parameters[i].name;
            }
        }
        
        signatureStream << L")";
        std::wstring signature = signatureStream.str();
        
        if (options.removeVoidParams) {
            signature = RemoveVoidFromParams(signature);
        }
        
        if (options.includeAddressComments && func.virtualAddress != 0) {
            ss << L"// Address: 0x" << std::hex << func.virtualAddress << L"\r\n";
        }
        
        ss << signature << L";\r\n";
    }
    
    return ss.str();
}

bool ExportEnhancer::ExportEnhancedHeader(const ClassInfo& cls, const std::wstring& filePath, const ExportOptions& options, NumberDisplayMode numberMode, bool expandBaseClasses, const ModuleInfo* moduleInfo) {
    std::wstring content;
    if (cls.isStruct) {
        content = PDBHeaderGenerator::GenerateStructDeclaration(cls, numberMode, expandBaseClasses, moduleInfo);
    } else if (cls.isUnion) {
        content = PDBHeaderGenerator::GenerateUnionDeclaration(cls, numberMode);
    } else {
        content = PDBHeaderGenerator::GenerateClassDeclaration(cls, numberMode, expandBaseClasses, moduleInfo);
    }
    
    if (options.flattenNamespaces) {
        content = FlattenName(content);
    }
    
    if (options.removeVoidParams) {
        content = RemoveVoidFromParams(content);
    }
    
    std::wofstream file(filePath);
    if (!file.is_open()) {
        return false;
    }
    
    file << content;
    file.close();
    return true;
}

bool ExportEnhancer::ExportAllEnhancedHeaders(const ModuleInfo& moduleInfo, const std::wstring& directoryPath, const ExportOptions& options, NumberDisplayMode numberMode, bool expandBaseClasses) {
    bool success = true;
    
    for (const auto& cls : moduleInfo.classes) {
        std::wstring filePath = directoryPath + L"\\" + cls.name + L".h";
        if (!ExportEnhancedHeader(cls, filePath, options, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }
    
    for (const auto& str : moduleInfo.structs) {
        std::wstring filePath = directoryPath + L"\\" + str.name + L".h";
        if (!ExportEnhancedHeader(str, filePath, options, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }
    
    for (const auto& uni : moduleInfo.unions) {
        std::wstring filePath = directoryPath + L"\\" + uni.name + L".h";
        if (!ExportEnhancedHeader(uni, filePath, options, numberMode, expandBaseClasses, &moduleInfo)) {
            success = false;
        }
    }
    
    return success;
}
